# 개발 환경
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3307/mango}
spring.datasource.username=${DB_USERNAME:mango}
spring.datasource.password=${DB_PASSWORD:mango_pass}

spring.jpa.show-sql=true
